### PR TITLE
@orta => Update attention color

### PR DESCRIPTION
**Pull request by alloy**
https://github.com/artsy/eigen/issues/644#issuecomment-121929994

### CODE REVIEW

**Comment by alloy** [comment]
Sigh. I don’t know why Travis is failing on this.

**Comment by alloy** [comment]
Ok green, I’m just gonna merge so that I can get on with the day and hopefully get the feeling I actually did something.

**Comment by orta** [comment]
:D

**Comment by orta** [comment]
So much random stuff to update when doing a pod update.

**Pull request merged**
